name: Prepare meta update PR in autoupdate repo

runs:
  using: "composite"
  steps:
    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Run go generate
      shell: bash
      working-directory: service-repository/
      run: go generate ./...
