name: Create pull request in remote repository
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      commit:
        required: true
        type: string
      assignee:
        required: true
        type: string
      setup-action:
        type: string
    secrets:
      AUTOMATION_APP_ID:
        required: true
      AUTOMATION_APP_PRIVATE_KEY:
        required: true

jobs:
  workflow_call:
    name: Create or update PR
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      # This is done, because setup-action will be called from here
      - uses: actions/checkout@v4
        with:
          path: current-go-repository
          ref: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          path: service-repository
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          submodules: true

      - name: Set openslides-go version
        working-directory: service-repository/
        run: |
          go get github.com/${{ github.repository_owner }}/openslides-go@${{ inputs.commit }}
          go mod tidy

      - name: Run setup-action
        if: inputs.setup-action != ''
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ./current-go-repository/.github/actions/${{ inputs.setup-action }}

      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v7
        with:
          path: service-repository
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update openslides-go
          branch: dep/update-meta-or-go-${{ github.ref_name }}
          delete-branch: true
          title: "Update openslides-go (${{ github.ref_name }})"
          body: "Triggered by commit [${{ inputs.commit }}](https://github.com/${{ github.repository_owner }}/openslides-go/commit/${{ inputs.commit }})"
          reviewers: ${{ inputs.assignee }}
          assignees: ${{ inputs.assignee }}
          labels: dependencies
